
name: Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
        lintTest:
          name: Lint test
          runs-on: ubuntu-latest
      
          strategy:
            matrix:
              node-version: [18.x]
      
          steps:
            - name: Checkout code
              uses: actions/checkout@v3
      
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
                cache: npm
      
            - name: Install dependencies
              run: npm install
      
            - name: Build
              run: npm run lint

        deploy:
          name: deployment
          runs-on: ubunto-latest
          needs: [lintTest]        
          strategy:
              matrix:
                node-version: [18.x]
        
          steps:
              - name: Checkout code
                uses: actions/checkout@v3
        
              - name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v3
                with:
                  node-version: ${{ matrix.node-version }}
                  cache: npm
        
              - name: Install dependencies
                run: npm install
        
              - name: Build
                run: npm run build


    
            
              

